name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
        
      - name: "Setup Gradle"
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4
        
      - name: "Make gradlew executable"
        run: chmod +x ./gradlew
        
      - name: "Execute Gradle build"
        run: ./gradlew build
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
            even-more-fish-plugin/*.jar
